<a href="https://colab.research.google.com/github/ArshockAbedan/DataScience/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Numpy

In [1]:
import numpy as np

1- ndarray

In [ ]:
# 1-dimentional array (Vector)
oneDim = np.array([1,2.0,3,4,5]) 
print(oneDim)
print("#Dimentions = ", oneDim.ndim)
print("Dimention = ", oneDim.shape)
print("Size = ", oneDim.size)
print("Array type = ", oneDim.dtype)

[1. 2. 3. 4. 5.]
#Dimentions =  1
Dimention =  (5,)
Size =  5
Array type =  float64


In [ ]:
# 2-dimentional array (matrix)
twoDim = np.array([[1,2],[3,4],[5,6],[7,8]])
print(twoDim)
print("#Dimentions = ", twoDim.ndim)
print("Dimention = ", twoDim.shape)
print("Size = ", twoDim.size)
print("Array type = ", twoDim.dtype)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
#Dimentions =  2
Dimention =  (4, 2)
Size =  8
Array type =  int64


In [ ]:
 # create ndarray from tuple
arrFromTuple = np.array([(1,'a',3.0),(2,'b',3.5)]) 
print(arrFromTuple)
print("#Dimensions =", arrFromTuple.ndim)
print("Dimension =", arrFromTuple.shape)
print("Size =", arrFromTuple.size)

[['1' 'a' '3.0']
 ['2' 'b' '3.5']]
#Dimensions = 2
Dimension = (2, 3)
Size = 6


There are several built-in functions in numpy that can be used to create ndarrays

In [ ]:
# random numbers from a uniform distribution between [0,1]
print(np.random.rand(5))

[0.45546452 0.92777663 0.23799251 0.18036565 0.76443055]


In [ ]:
# random numbers from a normal distribution
print(np.random.randn(5))

[ 0.01741878 -1.55969252 -1.92248774 -0.73226126 -0.17431855]


In [ ]:
# arrange is similar to range, but returns ndarray instead of list
print(np.arange(-10,10,2))

[-10  -8  -6  -4  -2   0   2   4   6   8]


In [ ]:
# reshape to a matrix
print(np.arange(12).reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# split interval [0,1] into 10 equally separated values
print(np.linspace(0,1,10))

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
# create ndarray with values from 10^-3 to 10^3
print(np.logspace(-3,3,7))

[1.e-03 1.e-02 1.e-01 1.e+00 1.e+01 1.e+02 1.e+03]


In [ ]:
# a matrix of zeros
print(np.zeros((4,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# a matrix of ones
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# a 3 x 3 identity matrix
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


2- Element-wise Operations

In [ ]:
x = np.array([1,2,3,4,5])

print(x + 1)      # addition
print(x - 1)      # subtraction
print(x * 2)      # multiplication
print(x // 2)     # integer division
print(x ** 2)     # square
print(x % 2)      # modulo  
print(1 / x)      # division

[2 3 4 5 6]
[0 1 2 3 4]
[ 2  4  6  8 10]
[0 1 1 2 2]
[ 1  4  9 16 25]
[1 0 1 0 1]
[1.         0.5        0.33333333 0.25       0.2       ]


In [ ]:
x = np.array([2,4,6,8,10])
y = np.array([1,2,3,4,5])

print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x // y)
print(x ** y)

[ 3  6  9 12 15]
[1 2 3 4 5]
[ 2  8 18 32 50]
[2. 2. 2. 2. 2.]
[2 2 2 2 2]
[     2     16    216   4096 100000]


**3- Indexing and Slicing**

In [ ]:
x = np.arange(-5,5)
print(x)

[-5 -4 -3 -2 -1  0  1  2  3  4]


In [ ]:
y = x[3:5] # y is a slice, i.e., pointer to a subarray in x
print(y)

[-2 -1]


In [ ]:
# modifying the value of y will change x
y[:] = 1000
print(x)
print(y)

[  -5   -4   -3 1000 1000    0    1    2    3    4]
[1000 1000]


In [ ]:
# makes a copy of the subarray
z = x[3:5].copy()
print(z)

[1000 1000]


In [ ]:
# modifying the value of z will not affect x
z[:] = 500
print(x)
print(z)

[  -5   -4   -3 1000 1000    0    1    2    3    4]
[500 500]


In [ ]:
#
# a 2-dim list
#
my2dlist = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]   
print(my2dlist)
print(my2dlist[2])        # access the third sublist
print(my2dlist[:][2])     # can't access third element of each sublist
# print(my2dlist[:,2])    # this will cause syntax error

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[9, 10, 11, 12]
[9, 10, 11, 12]


In [ ]:
my2darr = np.array(my2dlist)
print(my2darr)

print("===============")
# access the third row
print(my2darr[2][:])  

print("===============")
# access the third row
print(my2darr[2,:]) 

print("===============")
# access the third row (similar to 2d list)      
print(my2darr[:][2]) 

print("===============")
# access the third column    
print(my2darr[:,2])  

print("===============")
# access the first two rows & last two columns
print(my2darr[:2,2:])     

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 9 10 11 12]
[ 9 10 11 12]
[ 9 10 11 12]
[ 3  7 11]
[[3 4]
 [7 8]]


ndarray also supports boolean indexing.

In [3]:
my2array = np.arange(1,13,1).reshape(3,4)
print(my2array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
divBy3 = my2array[my2array % 3 == 0]
print(divBy3)

[ 3  6  9 12]


In [15]:
divBy3LastRow = my2array[2,my2array[2,:] % 3 ==0]
print(divBy3LastRow)

[ 9 12]


In [18]:
my2darr = np.arange(1,13,1).reshape(4,3)
print(my2darr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [20]:
# selected row indices
indeces = [2,1,3,0]
print(my2darr[indeces,:])

[[ 7  8  9]
 [ 4  5  6]
 [10 11 12]
 [ 1  2  3]]


In [21]:
# row index into my2darr
rowIndex = [0,0,1,2,3]

# column index into my2darr
columnIndex = [0,2,0,1,2]

print(my2darr[rowIndex,columnIndex])

[ 1  3  4  8 12]


***4- Numpy Arithmetic and Statistical Functions***

In [22]:
y = np.array([-1.4, 0.4, -3.2, 2.5, 3.4])
print(y)

[-1.4  0.4 -3.2  2.5  3.4]


In [23]:
print(np.abs(y))          # convert to absolute values
print(np.sqrt(abs(y)))    # apply square root to each element
print(np.sign(y))         # get the sign of each element
print(np.exp(y))          # apply exponentiation
print(np.sort(y))         # sort array

[1.4 0.4 3.2 2.5 3.4]
[1.18321596 0.63245553 1.78885438 1.58113883 1.84390889]
[-1.  1. -1.  1.  1.]
[ 0.24659696  1.4918247   0.0407622  12.18249396 29.96410005]
[-3.2 -1.4  0.4  2.5  3.4]


In [24]:
x = np.arange(-2,3)
y = np.random.rand(5)
print(x)
print(y)

[-2 -1  0  1  2]
[0.61580856 0.6888702  0.23284477 0.74008042 0.17062493]


In [27]:
# element-wise addition       x + y
print(np.add(x,y))   

# element-wise subtraction    x - y
print(np.subtract(x,y)) 

# element-wise multiplication x * y
print(np.multiply(x,y)) 

# element-wise division       x / y
print(np.divide(x,y)) 

# element-wise maximum        max(x,y)
print(np.maximum(x,y))       

[-5.2 -2.4  0.4  3.5  5.4]
[ 1.2  0.4 -0.4 -1.5 -1.4]
[6.4 1.4 0.  2.5 6.8]
[0.625      0.71428571 0.         0.4        0.58823529]
[-2.  -1.   0.4  2.5  3.4]


In [26]:
# generate a random vector
y = np.array([-3.2, -1.4, 0.4, 2.5, 3.4])   
print(y)

# min 
print("Min =", np.min(y)) 

# max 
print("Max =", np.max(y))   

# mean/average
print("Average =", np.mean(y))  

# standard deviation
print("Std deviation =", np.std(y))  

# sum 
print("Sum =", np.sum(y))

[-3.2 -1.4  0.4  2.5  3.4]
Min = -3.2
Max = 3.4
Average = 0.34000000000000014
Std deviation = 2.432776191925595
Sum = 1.7000000000000006


**5- Numpy linear algebra**

In [28]:
# create a 2 x 3 random matrix
X = np.random.randn(2,3)
print(X)

# matrix transpose operation X^T
print(X.T)

[[-1.15278261  1.84598316  0.8367118 ]
 [ 0.70646508 -0.0345475   1.06618285]]
[[-1.15278261  0.70646508]
 [ 1.84598316 -0.0345475 ]
 [ 0.8367118   1.06618285]]


In [30]:
# random vector 
Y = np.random.randn(3)
print(Y)

[-0.36691196  1.34605989  1.00630332]


In [31]:
# matrix-vector multiplication  X * y
print(X.dot(Y))

[3.74975947 0.76718986]


In [33]:
# matrix-matrix multiplication  X * X^T
print(X.dot(X.T))

[[5.43664821 0.01391301]
 [0.01391301 1.63703231]]


In [34]:
# matrix-matrix multiplication  X^T * X
print(X.T.dot(X))

[[ 1.82800066 -2.15242388 -0.21132586]
 [-2.15242388  3.40884736  1.50772194]
 [-0.21132586  1.50772194  1.8368325 ]]


In [35]:
X = np.random.randn(5,3)
print(X)

[[-0.54055127  0.59694949  0.1812366 ]
 [ 0.95956864 -1.09403626 -1.12045326]
 [ 1.8001721  -0.92906678  0.71687184]
 [ 0.03858329  0.53054719 -0.15611217]
 [ 0.5950227   0.05589164  1.16873054]]


In [37]:
# C = X^T * X is a square matrix
C = X.T.dot(X)
print(C)

[[ 4.8091279  -2.99123774  0.80677108]
 [-2.99123774  2.70103331  0.65048117]
 [ 0.80677108  0.65048117  3.19246953]]


In [39]:
# inverse of a square matrix
invC = np.linalg.inv(C)
print(invC)

[[ 1.37307879  1.6869479  -0.69071547]
 [ 1.6869479   2.4618968  -0.92793314]
 [-0.69071547 -0.92793314  0.67685918]]


In [40]:
# determinant of a square matrix
detC = np.linalg.det(C)
print(detC)

5.9718647529521025


In [42]:
# eigenvalue S and eigenvector U of a square matrix
S, U = np.linalg.eig(C)
print("eigenvalue = ", S)
print("eigenvector = ", U)

eigenvalue =  [6.94878842 0.24492174 3.50892058]
eigenvector =  [[ 0.82071292 -0.55813496  0.1221297 ]
 [-0.565955   -0.764904    0.30759846]
 [ 0.07826396  0.32156995  0.94364587]]
